export const LISTENERS_METADATA = 'LISTENERS_METADATA';
export const BOT_NAME = 'BOT_NAME';
export const BOT_OPTIONS = 'BOT_OPTIONS';
export const PAYMENTS_CONTROLLER = 'PAYMENTS_CONTROLLER';
export const PAYMENT_SERVICE_OPTIONS = 'PAYMENT_SERVICE_OPTIONS';
